# Generated by Django 3.2.6 on 2022-03-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='usage_fee',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='room_type',
            name='afternoon',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='room_type',
            name='evening',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='room_type',
            name='morning',
            field=models.FloatField(),
        ),
    ]
