# Generated by Django 3.2.6 on 2022-03-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20220304_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomLedger',
            fields=[
                ('room_ledger_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_use', models.DateField()),
                ('room_number', models.IntegerField()),
                ('room_type', models.IntegerField()),
                ('morning', models.IntegerField()),
                ('afternoon', models.IntegerField()),
                ('evening', models.IntegerField()),
            ],
        ),
    ]
