# Generated by Django 3.2.9 on 2022-03-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_roomledger_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomledger',
            name='date_of_use',
            field=models.CharField(max_length=50),
        ),
    ]
