# Generated by Django 3.2.9 on 2022-03-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_roomledger_date_of_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomledger',
            name='date_of_use',
            field=models.DateField(),
        ),
    ]
