# Generated by Django 3.2.9 on 2022-05-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_roomledger_date_of_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room_number',
            field=models.IntegerField(),
        ),
    ]
