# Generated by Django 3.2.9 on 2022-05-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_alter_reservation_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='scheduled_date_of_use',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='roomledger',
            name='date_of_use',
            field=models.TextField(),
        ),
    ]
